name: Cargo Release

on:
  # allows to manually run the job at any time
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Download libtorch Zip
        run: |
          curl -o libtorch.zip https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.0.0%2Bcu118.zip
      - name: Unzip libtorch
        run: |
          unzip libtorch.zip
      - name: Set up environment for `tch-rs`
        run: |
          echo "LIBTORCH=${{ github.workspace }}/libtorch" >> $GITHUB_ENV
      - name: Build release
        run: cargo build --release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
