name: Cargo Release

on:
  # allows to manually run the job at any time
  workflow_dispatch:
  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build release
        run: cargo build --release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
